export const moduleId = 'audit';

const demoLabel = 'Datos demo · no producción';
const institutions = ['Municipio Centro', 'Agua Norte', 'Servicios Urbanos Sur'];
const roles = ['mt_superadmin', 'municipal_admin', 'supervisor', 'brigade_member', 'citizen'];
const severities = ['info', 'low', 'medium', 'high', 'critical'];
const results = ['success', 'failed', 'denied', 'warning'];
const resources = ['ticket', 'audit_event', 'notification', 'membership', 'configuration', 'evidence', 'user'];

const ticketSteps = ['ticket_created','ticket_received','ticket_assigned','work_started','arrival_marked','evidence_added','pending_verification','ticket_approved','ticket_resolved','citizen_notified'];
const events = [
  ['AUD-240715-001','2026-07-15 08:10:11','Municipio Centro','ana.l***@demo.local','citizen','ticket_created','ticket','TK-10291','info','success','corr-ticket-10291','Citizen Portal','Ticket ciudadano creado'],
  ['AUD-240715-002','2026-07-15 08:10:12','Municipio Centro','system.audit','system','ticket_received','ticket','TK-10291','info','success','corr-ticket-10291','Municipal Panel','Recepción registrada'],
  ['AUD-240715-003','2026-07-15 08:20:40','Municipio Centro','maria.g***@demo.local','municipal_admin','ticket_assigned','ticket','TK-10291','medium','success','corr-ticket-10291','Municipal Panel','Asignación a brigada'],
  ['AUD-240715-004','2026-07-15 08:41:03','Municipio Centro','brigada.2@demo.local','supervisor','work_started','ticket','TK-10291','info','success','corr-ticket-10291','Brigade Portal','Trabajo iniciado'],
  ['AUD-240715-005','2026-07-15 09:05:33','Municipio Centro','brigada.2@demo.local','supervisor','evidence_added','evidence','EVD-883','low','success','corr-ticket-10291','Storage futuro','Evidencia agregada sin datos sensibles'],
  ['AUD-240715-006','2026-07-15 09:30:52','Municipio Centro','supervisor.z4@demo.local','supervisor','ticket_approved','ticket','TK-10291','medium','success','corr-ticket-10291','Municipal Panel','Validación de supervisor'],
  ['AUD-240715-007','2026-07-15 09:31:10','Municipio Centro','system.notifications','system','citizen_notified','notification','NTF-2401','info','success','corr-ticket-10291','Notifications V2','Notificación relacionada creada'],
  ['AUD-240715-008','2026-07-15 10:04:21','Agua Norte','login.demo@demo.local','municipal_admin','login_failed','user','USR-771','high','failed','corr-sec-771','Authentication','Múltiples logins fallidos'],
  ['AUD-240715-009','2026-07-15 10:06:44','Agua Norte','admin.agua@demo.local','municipal_admin','cross_tenant_access_attempt','ticket','TK-90011','critical','denied','corr-sec-tenant','Authentication','Intento cross-tenant bloqueado demo'],
  ['AUD-240715-010','2026-07-15 11:18:00','Servicios Urbanos Sur','mt.admin@demo.local','mt_superadmin','role_changed','membership','MBR-301','critical','success','corr-admin-301','Master Admin','Cambio de rol privilegiado demo'],
  ['AUD-240715-011','2026-07-15 12:22:18','Municipio Centro','config.admin@demo.local','municipal_admin','sensitive_config_changed','configuration','CFG-019','high','success','corr-cfg-019','Configuration','Cambio sensible de configuración'],
  ['AUD-240715-012','2026-07-15 13:07:09','Servicios Urbanos Sur','brigada.sur@demo.local','supervisor','evidence_rejected','evidence','EVD-901','medium','warning','corr-ticket-10308','Brigade Portal','Evidencia rechazada por validación'],
].map(([id,timestamp,institution,actor,role,action,resource,resourceId,severity,result,correlation,module,description], i) => ({ id,timestamp,institution,actor,role,action,resource,resourceId,severity,result,correlation,module,description, ip:'192.0.2.xxx', userAgent:'DemoBrowser/2.0 (redacted)', origin:'frontend-demo', duration:`${i * 7 + 3}s`, metadata:{ demo:true, tenant_id:`tenant_${institution.toLowerCase().replaceAll(' ','_')}`, redaction:'tokens/passwords/service_role excluded' }, before:{ status:i ? 'previous_demo_state' : 'none' }, after:{ status:action } }));

let alerts = [
  ['ALT-01','critical','open','Intento de acceso entre instituciones','corr-sec-tenant'],['ALT-02','high','open','Múltiples logins fallidos','corr-sec-771'],['ALT-03','critical','reviewed','Cambio de rol privilegiado','corr-admin-301'],['ALT-04','medium','open','Alto volumen de errores demo','corr-health-err'],['ALT-05','high','open','Actividad administrativa inusual','corr-admin-301'],['ALT-06','medium','open','Ausencia inesperada de eventos','corr-health-gap'],['ALT-07','high','reviewed','Fallo en cobertura de auditoría','corr-health-cover']
].map(([id,severity,status,title,correlation]) => ({ id,severity,status,title,correlation,note:'' }));

function badge(value){ return `<span class="aud-badge ${value}">${value}</span>`; }
function safeJson(obj){ return JSON.stringify(obj, null, 2).replace(/[<>&]/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;'}[c])); }

export function mount(container, context = {}) {
  if (!container) throw new Error('A mount container is required for audit.');
  container.dataset.v2Module = moduleId;
  const state = { tab:'Dashboard', selected:events[0], corr:'corr-ticket-10291', user:'maria.g***@demo.local', role:context.role || 'mt_superadmin' };
  container.innerHTML = `<style>${styles()}</style><section class="aud-shell"><header class="aud-hero"><div><p>${demoLabel}</p><h1>Audit V2 · Centro de trazabilidad</h1><span>Investigación visual de quién hizo qué, cuándo, desde qué institución y sobre qué recurso.</span></div><div class="aud-context"><label>Rol demo<select id="audRole">${['mt_superadmin','municipal_admin','supervisor'].map(r=>`<option ${r===state.role?'selected':''}>${r}</option>`).join('')}</select></label><label>Institución activa<select>${institutions.map(i=>`<option>${i}</option>`).join('')}</select></label></div></header><p class="aud-note"><b>Seguridad:</b> la seguridad real no debe depender del frontend. El aislamiento y autorización deberán aplicarse mediante Supabase Auth, RLS, funciones seguras y backend. No service_role en frontend.</p><nav class="aud-tabs">${['Dashboard','Explorador','Detalle','Correlation tracing','Usuarios','Instituciones','Seguridad','Alertas','Ticket timeline','Notifications V2','Exportación demo','Salud'].map((t,i)=>`<button class="${i?'':'active'}" data-tab="${t}">${t}</button>`).join('')}</nav><main id="audContent"></main></section>`;
  const draw = () => { container.querySelector('#audContent').innerHTML = render(state); bind(container,state,draw); };
  container.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{container.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active')); b.classList.add('active'); state.tab=b.dataset.tab; draw();}));
  draw();
}

function render(s){ return ({'Dashboard':dashboard,'Explorador':explorer,'Detalle':()=>detail(s.selected),'Correlation tracing':()=>correlation(s),'Usuarios':()=>users(s),'Instituciones':institutionsView,'Seguridad':security,'Alertas':alertsView,'Ticket timeline':ticketTimeline,'Notifications V2':notificationsLink,'Exportación demo':exportView,'Salud':health}[s.tab]||dashboard)(); }
function dashboard(){ const k=[['Eventos hoy',128],['Eventos críticos',4],['Eventos de seguridad',18],['Usuarios activos',42],['Instituciones con actividad',3],['Cambios de configuración',9],['Acciones administrativas',21],['Eventos de tickets',74],['Correlation IDs activos',16],['Cobertura de auditoría','97.4%']]; return `<section class="aud-grid kpis">${k.map(([a,b],i)=>`<article><small>${a}</small><strong>${b}</strong><div><i style="width:${(i+5)*8%100}%"></i></div><em>↗ tendencia demo</em></article>`).join('')}</section><section class="aud-panel"><h2>Centro visual profesional</h2><p>${demoLabel}. Preparado para v11_audit_events, institutions, memberships, tenant_id, RLS, Realtime, Edge Functions, Notifications V2, Storage V2 y observabilidad futura.</p></section>`; }
function explorer(){ return `<section class="aud-panel filters"><input id="q" placeholder="Buscar event ID, actor, recurso, correlation"><select id="fi"><option value="">Institución</option>${institutions.map(x=>`<option>${x}</option>`)}</select><select id="fac"><option value="">Actor</option>${[...new Set(events.map(e=>e.actor))].map(x=>`<option>${x}</option>`)}</select><select id="fr"><option value="">Rol</option>${roles.map(x=>`<option>${x}</option>`)}</select><select id="fa"><option value="">Acción</option>${[...new Set(events.map(e=>e.action))].map(x=>`<option>${x}</option>`)}</select><select id="fre"><option value="">Recurso</option>${resources.map(x=>`<option>${x}</option>`)}</select><select id="fs"><option value="">Severidad</option>${severities.map(x=>`<option>${x}</option>`)}</select><select id="fo"><option value="">Resultado</option>${results.map(x=>`<option>${x}</option>`)}</select><input type="date" value="2026-07-15"></section><section class="aud-panel"><div id="rows">${rows(events)}</div></section>`; }
function rows(list){ return list.map(e=>`<button class="aud-row" data-id="${e.id}"><b>${e.id}</b><time>${e.timestamp}</time><span>${e.institution}</span><span>${e.actor}</span><span>${e.role}</span><span>${e.action}</span><span>${e.resource}</span><span>${e.resourceId}</span>${badge(e.severity)}${badge(e.result)}<code>${e.correlation}</code><em>Ver detalle</em></button>`).join('') || '<p>No hay resultados demo.</p>'; }
function detail(e=events[0]){ return `<section class="aud-two"><article class="aud-panel"><h2>Detalle de evento ${e.id}</h2><dl>${['timestamp','institution','actor','role','action','resource','resourceId','result','severity','correlation','ip','userAgent','origin','module','description'].map(k=>`<dt>${k}</dt><dd>${e[k]}</dd>`).join('')}</dl></article><aside class="aud-panel"><h3>Metadata segura</h3><pre>${safeJson(e.metadata)}</pre><h3>Estado anterior</h3><pre>${safeJson(e.before)}</pre><h3>Estado nuevo</h3><pre>${safeJson(e.after)}</pre><p class="aud-note">IP anonimizada, email parcialmente redactado, metadata filtrada, ausencia de tokens, contraseñas, secretos y service_role. Minimización de datos aplicada.</p></aside></section>`; }
function correlation(s){ const ids=[...new Set(events.map(e=>e.correlation))]; const list=events.filter(e=>e.correlation===s.corr); return `<section class="aud-panel"><label>Correlation ID<select id="corr">${ids.map(id=>`<option ${id===s.corr?'selected':''}>${id}</option>`)}</select></label><ol class="timeline">${list.map(e=>`<li><b>${e.timestamp}</b> · ${e.actor} · ${e.module} · ${e.action} · ${e.resource}:${e.resourceId} · ${badge(e.result)} · duración ${e.duration}</li>`).join('')}</ol><p>Advertencias/errores demo: ${list.some(e=>e.result!=='success')?'revisar eventos no exitosos':'sin errores en esta cadena'}.</p></section>`; }
function users(s){ const users=[...new Set(events.map(e=>e.actor))]; const ev=events.filter(e=>e.actor===s.user); return `<section class="aud-two"><div class="aud-panel"><h2>Actividad por usuario</h2>${users.map(u=>`<button class="user" data-user="${u}">${u}</button>`).join('')}</div><div class="aud-panel"><h3>${s.user}</h3><p>Rol: ${ev[0]?.role||'demo'} · Institución: ${ev[0]?.institution||'demo'} · Último acceso demo: 2026-07-15 13:45</p><p>Eventos: ${ev.length} · Críticos: ${ev.filter(e=>e.severity==='critical').length} · Fallidos: ${ev.filter(e=>e.result!=='success').length}</p><ol class="timeline">${ev.map(e=>`<li>${e.timestamp} · ${e.action} · ${e.resourceId}</li>`).join('')}</ol></div></section>`; }
function institutionsView(){ return `<section class="aud-grid">${institutions.map(i=>{const ev=events.filter(e=>e.institution===i);return `<article class="aud-panel"><h2>${i}</h2><p><b>Actividad por institución</b></p><p>Eventos totales ${ev.length}</p><p>Usuarios activos ${new Set(ev.map(e=>e.actor)).size}</p><p>Tickets auditados ${ev.filter(e=>e.resource==='ticket').length}</p><p>Cambios config ${ev.filter(e=>e.resource==='configuration').length}</p><p>Acciones admin ${ev.filter(e=>e.role.includes('admin')).length}</p><p>Alertas ${alerts.filter(a=>ev.some(e=>e.correlation===a.correlation)).length}</p><p>Última actividad ${ev.at(-1)?.timestamp||'Sin actividad'}</p></article>`}).join('')}</section>`; }
function security(){ const actions=['login_success','login_failed','logout','access_denied','cross_tenant_access_attempt','role_changed','user_deactivated','sensitive_config_changed','critical_admin_action','authorization_error','evidence_rejected','repeated_retries']; return `<section class="aud-panel"><h2>Eventos de seguridad demo</h2><div class="aud-grid">${actions.map((a,i)=>`<article><h3>${a}</h3>${badge(severities[i%5])}<p>Institución explícita: ${institutions[i%3]}</p></article>`).join('')}</div></section>`; }
function alertsView(){ return `<section class="aud-panel filters"><select id="alertSeverity"><option value="">Severidad</option>${severities.map(s=>`<option>${s}</option>`)}</select><select id="alertStatus"><option value="">Estado</option><option>open</option><option>reviewed</option></select></section><section class="aud-panel" id="alertRows">${alertRows(alerts)}</section>`; }
function alertRows(list){ return list.map(a=>`<article class="alert" data-alert="${a.id}"><h3>${a.id} · ${a.title}</h3>${badge(a.severity)} ${badge(a.status)} <code>${a.correlation}</code><textarea placeholder="Añadir nota demo">${a.note}</textarea><button data-review="${a.id}">Marcar revisada visualmente</button><button>Ver detalle</button></article>`).join(''); }
function ticketTimeline(){ return `<section class="aud-panel"><h2>Timeline completo de ticket · corr-ticket-10291</h2><ol class="timeline">${ticketSteps.map((s,i)=>`<li><b>${s}</b> → actor demo · módulo ${i%2?'Municipal/Brigade':'Citizen/Notifications'} · resultado success · +${i*4} min</li>`).join('')}</ol></section>`; }
function notificationsLink(){ return `<section class="aud-panel"><h2>Relación con Notifications V2</h2><p>Evento de negocio → evento de auditoría → notificación generada → estado de entrega.</p><button data-tablink="Explorador">Abrir evento auditado</button><button>Simular navegación a Notifications V2 / NTF-2401</button><dl><dt>Business event</dt><dd>ticket_resolved</dd><dt>Audit event</dt><dd>AUD-240715-007</dd><dt>Notificación</dt><dd>NTF-2401 · delivered</dd></dl></section>`; }
function exportView(){ return `<section class="aud-panel"><h2>Exportación demo</h2><button>Exportar CSV demo</button><button>Exportar JSON demo</button><button>Generar reporte de auditoría demo</button><p class="aud-note">No crea archivos reales ni exporta información sensible.</p></section>`; }
function health(){ const mods=['Authentication','Citizen Portal','Municipal Panel','Brigade Portal','Master Admin','Configuration','Notifications','Storage futuro']; return `<section class="aud-grid">${mods.map((m,i)=>`<article class="aud-panel"><h3>${m}</h3><p>Captura de eventos: operativa demo</p><p>Persistencia: preparada</p><p>Correlation IDs: ${98-i}%</p><p>Cobertura: ${92+i%6}%</p><p>Eventos fallidos: ${i}</p><p>Latencia: ${40+i*11}ms</p><p>Último evento recibido: 2026-07-15 13:${10+i}</p><p>Integridad de cadena: ${i===7?'futura':'ok demo'}</p></article>`).join('')}</section>`; }
function bind(c,s,draw){ c.querySelectorAll('.aud-row').forEach(r=>r.addEventListener('click',()=>{s.selected=events.find(e=>e.id===r.dataset.id); c.querySelector('[data-tab="Detalle"]').click();})); c.querySelector('#corr')?.addEventListener('change',e=>{s.corr=e.target.value;draw();}); c.querySelectorAll('.user').forEach(b=>b.addEventListener('click',()=>{s.user=b.dataset.user;draw();})); c.querySelector('#alertSeverity')?.addEventListener('input',()=>filterAlerts(c)); c.querySelector('#alertStatus')?.addEventListener('input',()=>filterAlerts(c)); c.querySelectorAll('[data-review]').forEach(b=>b.addEventListener('click',()=>{const a=alerts.find(x=>x.id===b.dataset.review); if(a)a.status='reviewed';draw();})); ['q','fi','fac','fr','fa','fre','fs','fo'].forEach(id=>c.querySelector('#'+id)?.addEventListener('input',()=>{const vals=Object.fromEntries(['q','fi','fac','fr','fa','fre','fs','fo'].map(x=>[x,c.querySelector('#'+x)?.value||''])); const filtered=events.filter(e=>(!vals.q||Object.values(e).join(' ').toLowerCase().includes(vals.q.toLowerCase()))&&(!vals.fi||e.institution===vals.fi)&&(!vals.fac||e.actor===vals.fac)&&(!vals.fr||e.role===vals.fr)&&(!vals.fa||e.action===vals.fa)&&(!vals.fre||e.resource===vals.fre)&&(!vals.fs||e.severity===vals.fs)&&(!vals.fo||e.result===vals.fo)); c.querySelector('#rows').innerHTML=rows(filtered);})); }
function filterAlerts(c){ const sev=c.querySelector('#alertSeverity')?.value||''; const st=c.querySelector('#alertStatus')?.value||''; c.querySelector('#alertRows').innerHTML=alertRows(alerts.filter(a=>(!sev||a.severity===sev)&&(!st||a.status===st))); }
function styles(){ return `.aud-shell{font-family:Inter,system-ui,sans-serif;background:#f4f7fb;color:#102033;padding:24px}.aud-hero{display:flex;justify-content:space-between;gap:20px;background:linear-gradient(135deg,#111827,#0f766e);color:white;border-radius:24px;padding:28px}.aud-hero p{color:#fde68a;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.aud-context,.filters{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.aud-tabs{display:flex;gap:8px;overflow:auto;padding:16px 0}.aud-tabs button,.aud-panel button,.user{border:0;border-radius:999px;padding:10px 14px;background:#ccfbf1;color:#115e59;font-weight:800;cursor:pointer;margin:3px}.aud-tabs .active{background:#0f766e;color:white}.aud-note{background:#fffbeb;border:1px solid #fde68a;border-radius:14px;padding:12px}.aud-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px}.aud-panel,.kpis article{background:white;border:1px solid #d8e2ef;border-radius:20px;padding:18px;box-shadow:0 10px 25px #0f172a12;margin-bottom:16px}.kpis strong{font-size:2rem;display:block}.kpis div{height:8px;background:#e5e7eb;border-radius:999px}.kpis i{display:block;height:100%;background:#14b8a6;border-radius:999px}.aud-row{width:100%;display:grid;grid-template-columns:1.1fr 1fr 1fr 1fr .8fr 1fr .8fr .8fr .6fr .6fr 1fr .7fr;gap:8px;text-align:left;align-items:center;background:#f8fafc;border:1px solid #e2e8f0;border-radius:14px;margin:8px 0;padding:12px}.aud-badge{border-radius:999px;padding:5px 8px;font-weight:900;background:#e5e7eb}.critical,.failed,.denied{background:#fee2e2;color:#991b1b}.high,.warning{background:#fef3c7;color:#92400e}.medium{background:#dbeafe;color:#1d4ed8}.info,.success,.reviewed{background:#dcfce7;color:#166534}.low,.open{background:#ede9fe;color:#5b21b6}.aud-two{display:grid;grid-template-columns:minmax(0,1fr) minmax(320px,.8fr);gap:16px}dt{font-weight:900}dd{margin:0 0 8px}.timeline{border-left:4px solid #5eead4;padding-left:18px}.timeline li{margin:12px 0}pre,code{white-space:pre-wrap;background:#f1f5f9;border-radius:10px;padding:4px}textarea,input,select{width:100%;border:1px solid #cbd5e1;border-radius:12px;padding:10px}@media(max-width:850px){.aud-shell{padding:12px}.aud-hero,.aud-two{display:grid;grid-template-columns:1fr}.aud-row{grid-template-columns:1fr}.aud-tabs button{white-space:nowrap}}`; }
