import { config, signIn, service, user, rpcAnon, rpcAsUser, assert, expectDenied } from './supabase-http.mjs';

config();
const password = process.env.SAIBOT_DEV_TEST_PASSWORD;
const suffix = process.env.SAIBOT_DEV_TEST_SUFFIX || '001';
if (!password) throw new Error('Falta SAIBOT_DEV_TEST_PASSWORD. Ejecuta primero seed-v11.mjs.');
const domain = `saibot-dev-${suffix}.invalid`;
const login = async (name) => signIn(`${name}@${domain}`, password);
const sessions = Object.fromEntries(await Promise.all(['admin-a','supervisor-a','brigade-a','admin-b','brigade-b','new-user'].map(async (name) => [name, await login(name)])));
const token = (name) => sessions[name].access_token;
const institutions = await service(`/rest/v1/v11_institutions?slug=in.(saibot-dev-a-${suffix},saibot-dev-b-${suffix})&select=id,slug`);
const a = institutions.find((item) => item.slug === `saibot-dev-a-${suffix}`); const b = institutions.find((item) => item.slug === `saibot-dev-b-${suffix}`);
assert(a && b, 'No se encontraron instituciones sintéticas; ejecuta el seed.');
const brigades = await service(`/rest/v1/v11_brigades?institution_id=in.(${a.id},${b.id})&select=id,institution_id`);
const brigadeA = brigades.find((item) => item.institution_id === a.id); const brigadeB = brigades.find((item) => item.institution_id === b.id);
assert(brigadeA && brigadeB, 'No se encontraron brigadas sintéticas.');
const newUserMemberships = await user(`/rest/v1/v11_memberships?user_id=eq.${sessions['new-user'].user.id}&select=id`, token('new-user'));
assert(newUserMemberships.length === 0, 'Usuario nuevo recibió una membresía inesperada.');

const citizenA = await rpcAnon('v11_create_citizen_ticket', { target_institution: a.id, ticket_category: 'Residuos', ticket_description: 'Ticket sintético para validación de seguridad.', ticket_sector: 'Sector A', ticket_location_text: 'Datos sintéticos' });
const citizenB = await rpcAnon('v11_create_citizen_ticket', { target_institution: b.id, ticket_category: 'Residuos', ticket_description: 'Ticket sintético para aislamiento.', ticket_sector: 'Sector B', ticket_location_text: 'Datos sintéticos' });
const ticketA = Array.isArray(citizenA) ? citizenA[0] : citizenA; const ticketB = Array.isArray(citizenB) ? citizenB[0] : citizenB;
assert(ticketA?.public_id && ticketA?.tracking_secret, 'La creación ciudadana A no devolvió seguimiento.');
const lookup = await rpcAnon('v11_get_citizen_ticket', { ticket_public_id: ticketA.public_id, provided_secret: ticketA.tracking_secret });
assert((Array.isArray(lookup) ? lookup[0] : lookup)?.public_id === ticketA.public_id, 'Seguimiento ciudadano válido falló.');
const invalidLookup = await rpcAnon('v11_get_citizen_ticket', { ticket_public_id: ticketA.public_id, provided_secret: '0'.repeat(48) });
assert(Array.isArray(invalidLookup) && invalidLookup.length === 0, 'Seguimiento inválido filtró el ticket.');

const rowsA = await user('/rest/v1/v11_tickets?institution_id=eq.' + b.id + '&select=id', token('admin-a'));
assert(rowsA.length === 0, 'Administrador A pudo ver tickets de B.');
await expectDenied(() => user('/rest/v1/v11_memberships', token('supervisor-a'), { method: 'POST', body: { institution_id: a.id, user_id: sessions['new-user'].user.id, role: 'brigade_member', active: true } }), 'Supervisor administra membresías');
const rawA = await service(`/rest/v1/v11_tickets?public_id=eq.${ticketA.public_id}&select=id,version,status`); const rawTicketA = rawA[0];
await expectDenied(() => rpcAsUser('v11_assign_ticket', token('brigade-a'), { target_ticket: rawTicketA.id, target_brigade: brigadeA.id, expected_version: rawTicketA.version }), 'Brigada asigna ticket');
const assigned = await rpcAsUser('v11_assign_ticket', token('admin-a'), { target_ticket: rawTicketA.id, target_brigade: brigadeA.id, expected_version: rawTicketA.version });
const assignedTicket = Array.isArray(assigned) ? assigned[0] : assigned;
assert(assignedTicket.status === 'assigned', 'Asignación no cambió el estado.');
const brigadeTickets = await user('/rest/v1/v11_tickets?select=id,institution_id&assigned_brigade_id=eq.' + brigadeA.id, token('brigade-a'));
assert(brigadeTickets.some((item) => item.id === rawTicketA.id) && brigadeTickets.every((item) => item.institution_id === a.id), 'Brigada A recibió tickets incorrectos.');
const started = await rpcAsUser('v11_start_ticket_work', token('brigade-a'), { target_ticket: rawTicketA.id, expected_version: assignedTicket.version });
const startedTicket = Array.isArray(started) ? started[0] : started;
await expectDenied(() => rpcAsUser('v11_start_ticket_work', token('brigade-a'), { target_ticket: rawTicketA.id, expected_version: assignedTicket.version }), 'Transición con versión obsoleta');
const resolutionPath = `${a.id}/${rawTicketA.id}/resolution/synthetic.jpg`;
await service(`/storage/v1/object/resolution-evidence-v11/${resolutionPath}`, { method: 'POST', rawBody: Buffer.from([0xff, 0xd8, 0xff, 0xd9]), headers: { 'content-type': 'image/jpeg', 'x-upsert': 'true' } });
const submitted = await rpcAsUser('v11_submit_ticket_resolution', token('brigade-a'), { target_ticket: rawTicketA.id, expected_version: startedTicket.version, evidence_path: resolutionPath, resolution_note: 'Evidencia sintética.' });
const submittedTicket = Array.isArray(submitted) ? submitted[0] : submitted;
assert(submittedTicket.status === 'pending_verification', 'La resolución no quedó pendiente de verificación.');
const returned = await rpcAsUser('v11_review_ticket_resolution', token('supervisor-a'), { target_ticket: rawTicketA.id, expected_version: submittedTicket.version, approve: false, review_note: 'Revisión sintética requerida.' });
const returnedTicket = Array.isArray(returned) ? returned[0] : returned;
assert(returnedTicket.status === 'in_progress', 'La devolución no restauró el trabajo en proceso.');
const submittedAgain = await rpcAsUser('v11_submit_ticket_resolution', token('brigade-a'), { target_ticket: rawTicketA.id, expected_version: returnedTicket.version, evidence_path: resolutionPath, resolution_note: 'Evidencia sintética revisada.' });
const submittedAgainTicket = Array.isArray(submittedAgain) ? submittedAgain[0] : submittedAgain;
const resolved = await rpcAsUser('v11_review_ticket_resolution', token('supervisor-a'), { target_ticket: rawTicketA.id, expected_version: submittedAgainTicket.version, approve: true, review_note: null });
const resolvedTicket = Array.isArray(resolved) ? resolved[0] : resolved;
assert(resolvedTicket.status === 'resolved', 'La aprobación no resolvió el ticket.');
await expectDenied(() => user('/rest/v1/v11_audit_events', token('brigade-a'), { method: 'POST', body: { institution_id: a.id, entity_type: 'ticket', entity_id: rawTicketA.id, action: 'forged' } }), 'Inserción de auditoría cliente');
const audit = await user(`/rest/v1/v11_audit_events?entity_id=eq.${rawTicketA.id}&select=action`, token('supervisor-a'));
assert(['assigned', 'work_started', 'resolution_submitted', 'resolution_returned', 'resolution_approved'].every((action) => audit.some((event) => event.action === action)), 'Faltan eventos de auditoría.');
const foreignRaw = await service(`/rest/v1/v11_tickets?public_id=eq.${ticketB.public_id}&select=id`); const ticketBId = foreignRaw[0].id;
await expectDenied(() => user(`/storage/v1/object/resolution-evidence-v11/${b.id}/${ticketBId}/resolution/test.jpg`, token('brigade-a'), { method: 'POST', rawBody: Buffer.from([0xff, 0xd8, 0xff, 0xd9]), headers: { 'content-type': 'image/jpeg' } }), 'Carga Storage de brigada A a ticket B');
console.log(JSON.stringify({ status: 'passed', cases: ['profile-bootstrap','citizen-create-and-lookup','tenant-isolation','role-denials','assignment','brigade-access','state-conflict','verification-return-approve','audit','storage-rls'], final_status: resolvedTicket.status }, null, 2));
