export const contentStatuses = {
  DRAFT: 'draft',
  REVIEWED: 'reviewed',
  PUBLISHED: 'published',
};

export const municipalConfig = {
  municipality: {
    name: 'Ayuntamiento Municipal de Laguna Salada',
    shortName: 'Laguna Salada',
    tagline: 'Asistente Virtual Municipal',
  },
  branding: {
    primaryColor: '#075e54',
    secondaryColor: '#128c7e',
    backgroundColor: '#e5ddd5',
    logoUrl: '../../images/logo.png',
  },
  institutionalContent: {
    history: {
      status: contentStatuses.PUBLISHED,
      title: 'Historia del municipio',
      body: 'Laguna Salada es uno de los tres municipios de la provincia Valverde, ubicado en la región Cibao Noroeste de la República Dominicana.\n\nFue constituido como municipio mediante la Ley 916, promulgada el 12 de agosto de 1978.\n\nLimita al norte con la provincia Puerto Plata, al sur con Santa Cruz de Mao, al este con Esperanza y al oeste con la provincia Monte Cristi.\n\nSu desarrollo ha estado estrechamente relacionado con la agricultura, el comercio y el crecimiento de sus comunidades.',
      source: 'Contenido recuperado desde V1 local del proyecto.',
    },
    population: {
      status: contentStatuses.PUBLISHED,
      summaryValidated: true,
      title: 'Población',
      total: '10,627 habitantes',
      urbanRural: 'Información pendiente de validación oficial',
      growth: 'Información pendiente de validación oficial',
      communities: ['Cabecera municipal de Laguna Salada', 'Jaibón', 'La Caya', 'Cruce de Guayacanes'],
      source: 'X Censo Nacional de Población y Vivienda 2022, Oficina Nacional de Estadística (ONE). Contenido recuperado desde V1 local del proyecto.',
      year: '2022',
      note: 'Esta información corresponde específicamente a Laguna Salada y se presenta separada de los distritos municipales de Jaibón, La Caya y Cruce de Guayacanes.',
    },
    territorialArea: {
      status: contentStatuses.PUBLISHED,
      summaryValidated: false,
      valueKm2: '',
      source: 'Pendiente de validación oficial',
      year: '',
    },
    economy: {
      status: contentStatuses.PUBLISHED,
      title: 'Economía',
      generalDescription: 'La economía de Laguna Salada está fuertemente vinculada a la agricultura, el comercio y los servicios locales.',
      agriculture: 'La actividad agrícola forma parte esencial de la vida productiva del municipio y continúa siendo uno de los ejes estratégicos para el crecimiento económico local.',
      commerce: 'El comercio local y los servicios de proximidad sostienen parte de la dinámica diaria del municipio.',
      productiveActivities: ['Agricultura', 'Comercio local', 'Servicios municipales y comunitarios'],
      summaryValidated: true,
      employmentEntrepreneurship: 'El empleo y el emprendimiento local se describen de forma cualitativa hasta contar con estadísticas oficiales validadas.',
      opportunities: 'Oportunidades económicas pendientes de ampliación mediante planificación institucional y fuentes oficiales.',
      officialFigures: 'Información pendiente de validación oficial',
      source: 'Contenido recuperado desde V1 local del proyecto; cifras económicas oficiales pendientes de validación.',
    },
    landmarks: [
      {
        id: 'parque-maximo-gomez',
        status: contentStatuses.PUBLISHED,
        name: 'Parque Municipal Mirador del Valle “Máximo Gómez”',
        photoUrl: './assets/placeholder-landmark.svg',
        sourceImage: 'images/parque-maximo-gomez.png',
        description: 'Uno de los principales espacios públicos de Laguna Salada, dedicado al encuentro, la recreación y la convivencia de la comunidad.',
        importance: 'Espacio de encuentro comunitario, recreación y convivencia municipal.',
        location: 'Referencia municipal pendiente de validación oficial.',
      },
      {
        id: 'palacio-municipal',
        status: contentStatuses.PUBLISHED,
        name: 'Palacio Municipal de Laguna Salada',
        photoUrl: '../../images/palacio-municipal.png',
        description: 'Sede del gobierno local y centro de la administración municipal de Laguna Salada, provincia Valverde.',
        importance: 'Centro de la administración municipal y referencia institucional del gobierno local.',
        location: 'C/ 30 de Mayo No. 123, Centro del Pueblo, Laguna Salada.',
      },
      {
        id: 'parroquia-san-antonio',
        status: contentStatuses.PUBLISHED,
        name: 'Parroquia San Antonio de Padua',
        photoUrl: './assets/placeholder-landmark.svg',
        sourceImage: 'images/parroquia-san-antonio.png',
        description: 'Espacio religioso vinculado a la vida espiritual y comunitaria de Laguna Salada y a la tradición de San Antonio de Padua.',
        importance: 'Referencia espiritual y cultural asociada a la tradición de San Antonio de Padua.',
        location: 'Ubicación pendiente de validación oficial.',
      },
      {
        id: 'cementerio-municipal',
        status: contentStatuses.PUBLISHED,
        name: 'Cementerio Municipal de Laguna Salada',
        photoUrl: '../../images/cementerio-municipal.jpeg',
        description: 'Espacio municipal destinado al descanso y memoria de los seres queridos de la comunidad de Laguna Salada.',
        importance: 'Lugar de memoria comunitaria y servicio municipal.',
        location: 'Ubicación pendiente de validación oficial.',
      },
      {
        id: 'archivo-futuro',
        status: contentStatuses.REVIEWED,
        name: 'Lugar emblemático pendiente de publicación',
        photoUrl: './assets/placeholder-landmark.svg',
        description: 'Registro revisado no visible hasta publicación oficial.',
        importance: 'Pendiente de publicación.',
        location: 'Pendiente de publicación.',
      },
    ],
    authorities: {
      mayor: {
        id: 'mayor',
        status: contentStatuses.DRAFT,
        menuLabel: 'Conoce a tu alcalde',
        photoUrl: './assets/placeholder-authority.svg',
        name: '[PENDIENTE: nombre oficial del alcalde]',
        role: 'Alcalde municipal',
        term: '[PENDIENTE: período oficial]',
        biography: '[PENDIENTE: biografía oficial validada por el Ayuntamiento]',
        career: '[PENDIENTE: trayectoria oficial validada por el Ayuntamiento]',
        functions: ['[PENDIENTE: función oficial 1]', '[PENDIENTE: función oficial 2]', '[PENDIENTE: función oficial 3]'],
        institutionalMessage: '[PENDIENTE: mensaje institucional oficial]',
      },
      deputyMayor: {
        id: 'deputyMayor',
        status: contentStatuses.DRAFT,
        menuLabel: 'Conoce a tu vicealcaldesa',
        photoUrl: './assets/placeholder-authority.svg',
        name: '[PENDIENTE: nombre oficial de la vicealcaldesa]',
        role: 'Vicealcaldesa municipal',
        term: '[PENDIENTE: período oficial]',
        biography: '[PENDIENTE: biografía oficial validada por el Ayuntamiento]',
        career: '[PENDIENTE: trayectoria oficial validada por el Ayuntamiento]',
        functions: ['[PENDIENTE: función oficial 1]', '[PENDIENTE: función oficial 2]', '[PENDIENTE: función oficial 3]'],
        institutionalMessage: '[PENDIENTE: mensaje institucional oficial]',
      },
    },
    council: [
      { id: 'council-pending-1', status: contentStatuses.DRAFT, name: '[PENDIENTE: nombre oficial]', role: 'Concejo municipal', commission: '[PENDIENTE: comisión oficial]', biography: '[PENDIENTE: reseña oficial validada]' },
    ],
  },
  contacts: {
    title: 'Contactos y horarios',
    phone: '[PENDIENTE: teléfono oficial]',
    email: '[PENDIENTE: correo oficial]',
    address: '[PENDIENTE: dirección oficial]',
    openingHours: '[PENDIENTE: horarios oficiales]',
  },

  serviceDesk: {
    folioPrefix: 'SOL-',
    statuses: ['Recibida', 'Asignada', 'En proceso', 'En revisión', 'Resuelta', 'Cerrada'],
    exceptionalStatuses: ['Cancelada', 'Rechazada'],
    citizenClosure: {
      resolvedPrompt: '¿Confirmas que el servicio fue realizado satisfactoriamente?',
      confirmLabel: '👍 Sí, confirmar y cerrar',
      reviewLabel: '⚠️ No, necesito revisión',
      reviewTransition: 'Mantener trazabilidad y devolver a En revisión',
    },
    certificationPickup: {
      place: '[PENDIENTE: lugar oficial de retiro]',
      hours: '[PENDIENTE: horario oficial de retiro]',
      requirements: ['[PENDIENTE: requisitos oficiales para retirar]'],
    },
    notifications: {
      Recibida: '✅ Hemos recibido tu solicitud {{folio}}.',
      Asignada: '👷 Tu solicitud fue asignada al área responsable.',
      'En proceso': '🔧 Ya estamos trabajando en tu solicitud.',
      'En revisión': '🔎 El trabajo o trámite está siendo revisado.',
      ResueltaServicio: '✅ Tu solicitud ha sido atendida.',
      ResueltaCertificacion: '📄 Tu documento está listo para retiro.',
    },
    currency: 'RD$',
    priceDisclaimer: 'Precio demo · sujeto a validación oficial del ayuntamiento',
    services: [
      { id: 'limpieza-ornato', label: '🧹 Limpieza y ornato', department: 'Limpieza y Ornato', assignmentTarget: 'brigade', requiresSector: true, requiresLocation: true, evidence: 'optional', flow: 'operational-description', subtypes: [
        { label: 'Retiro de escombros', price: 1500, price_status: 'demo', free: false, requires_evaluation: false, payment_required: false, payment_instructions: '', fee_notes: 'Precio demo · sujeto a validación oficial del ayuntamiento' },
        { label: 'Recogida especial', price: 2000, price_status: 'demo', free: false, requires_evaluation: false, payment_required: false, payment_instructions: '', fee_notes: 'Precio demo · sujeto a validación oficial del ayuntamiento' },
        { label: 'Limpieza de espacio público', price: null, price_status: 'demo', free: true, requires_evaluation: true, payment_required: false, payment_instructions: '', fee_notes: 'Gratis / sujeto a evaluación · Precio demo · sujeto a validación oficial del ayuntamiento' },
      ] },
      { id: 'poda-areas-verdes', label: '🌳 Poda y áreas verdes', department: 'Ornato y Áreas Verdes', assignmentTarget: 'brigade', requiresSector: true, requiresLocation: true, evidence: 'recommended', flow: 'operational-description', subtypes: [
        { label: 'Poda de árbol', price: 1500, price_status: 'demo', free: false, requires_evaluation: false, payment_required: false, payment_instructions: '', fee_notes: 'Precio demo · sujeto a validación oficial del ayuntamiento' },
        { label: 'Árbol peligroso', price: null, price_status: 'demo', free: true, requires_evaluation: true, payment_required: false, payment_instructions: '', fee_notes: 'Gratis / sujeto a evaluación · Precio demo · sujeto a validación oficial del ayuntamiento' },
        { label: 'Mantenimiento de área verde', price: 2500, price_status: 'demo', free: false, requires_evaluation: false, payment_required: false, payment_instructions: '', fee_notes: 'Precio demo · sujeto a validación oficial del ayuntamiento' },
      ] },
      { id: 'alumbrado-publico', label: '💡 Alumbrado público', department: 'Alumbrado Público', assignmentTarget: 'brigade', requiresSector: true, requiresLocation: true, evidence: 'optional', flow: 'lighting-reference', subtypes: [
        { label: 'Luminaria averiada', price: null, price_status: 'demo', free: true, requires_evaluation: false, payment_required: false, payment_instructions: '', fee_notes: 'Precio demo · sujeto a validación oficial del ayuntamiento' },
        { label: 'Zona oscura', price: null, price_status: 'demo', free: true, requires_evaluation: false, payment_required: false, payment_instructions: '', fee_notes: 'Precio demo · sujeto a validación oficial del ayuntamiento' },
        { label: 'Evaluación de iluminación', price: null, price_status: 'demo', free: true, requires_evaluation: false, payment_required: false, payment_instructions: '', fee_notes: 'Precio demo · sujeto a validación oficial del ayuntamiento' },
      ] },
      { id: 'certificaciones-documentos', label: '📄 Certificaciones y documentos', department: 'Secretaría Municipal', assignmentTarget: 'administrative_department', requiresSector: false, requiresLocation: false, evidence: 'not_required', flow: 'certification', requirementsPrompt: 'Indica la información o requisitos disponibles para el documento solicitado.', subtypes: [
        { label: 'Certificación municipal', price: 1500, price_status: 'demo', free: false, requires_evaluation: false, payment_required: false, payment_instructions: '', fee_notes: 'Precio demo · sujeto a validación oficial del ayuntamiento' },
        { label: 'Constancia municipal', price: 2000, price_status: 'demo', free: false, requires_evaluation: false, payment_required: false, payment_instructions: '', fee_notes: 'Precio demo · sujeto a validación oficial del ayuntamiento' },
        { label: 'Otro documento disponible', price: 3000, price_status: 'demo', free: false, requires_evaluation: false, payment_required: false, payment_instructions: '', fee_notes: 'Precio demo · sujeto a validación oficial del ayuntamiento' },
      ] },
      { id: 'espacios-servicios-municipales', label: '🏛️ Uso de espacios y servicios municipales', department: 'Servicios Municipales', assignmentTarget: 'administrative_department', requiresSector: false, requiresLocation: false, evidence: 'not_required', flow: 'space-use', subtypes: [
        { label: 'Solicitud de parque o plaza', price: 2000, price_status: 'demo', free: false, requires_evaluation: false, payment_required: false, payment_instructions: '', fee_notes: 'Precio demo · sujeto a validación oficial del ayuntamiento' },
        { label: 'Instalación municipal', price: 3000, price_status: 'demo', free: false, requires_evaluation: false, payment_required: false, payment_instructions: '', fee_notes: 'Precio demo · sujeto a validación oficial del ayuntamiento' },
        { label: 'Actividad comunitaria', price: null, price_status: 'demo', free: true, requires_evaluation: true, payment_required: false, payment_instructions: '', fee_notes: 'Gratis / sujeto a evaluación · Precio demo · sujeto a validación oficial del ayuntamiento' },
      ] },
    ],
  },
  reportCategories: [
    { id: 'trash', label: '🗑️ Basura acumulada', requiresEvidence: true },
    { id: 'light', label: '💡 Luminaria dañada', requiresEvidence: true },
    { id: 'road', label: '🛣️ Calle deteriorada', requiresEvidence: true },
    { id: 'tree', label: '🌳 Árbol caído', requiresEvidence: true },
    { id: 'blocked-road', label: '🚧 Obstrucción de vía', requiresEvidence: true },
    { id: 'other', label: '➕ Otro problema municipal', requiresEvidence: false },
  ],
  sectors: [
    'San Antonio',
    'Puerto Rico',
    'La Curva',
    'Pueblo Nuevo',
    'Las Flores',
    'Alto de La Hicotea',
  ],
  reportPolicy: {
    activeInstitutionSlug: 'laguna-salada',
    askMunicipality: false,
    allowLocationOmission: false,
    requireEvidenceByDefault: false,
    demoGps: {
      latitude: 19.6504,
      longitude: -71.0934,
      accuracyMeters: 35,
      label: 'GPS demo Laguna Salada · no es ubicación real del ciudadano',
    },
  },
  futureContracts: {
    whatsappLocationMessage: { type: 'location', latitude: 'number', longitude: 'number', name: 'string | null', address: 'string | null' },
    whatsappEvidenceMessage: { type: 'image | document', mediaId: 'string', caption: 'string | null' },
    supabaseEvidenceStorage: { bucket: 'ticket-evidence-v11', path: '<institution_id>/pending/<filename>', uploadPending: true, status: 'BLOCKED_UNTIL_EDGE_FUNCTION' },
  },

};

export const demoMunicipalConfig = {
  ...municipalConfig,
  municipality: { name: 'Municipio Demo', shortName: 'Demo', tagline: 'Asistente Virtual Municipal Demo' },
  reportPolicy: { ...municipalConfig.reportPolicy, activeInstitutionSlug: 'demo-generico', demoGps: undefined },
  institutionalContent: {
    history: { status: contentStatuses.PUBLISHED, title: 'Historia del municipio', body: 'Información demo neutral pendiente de validación oficial.', source: 'Configuración demo.' },
    population: { status: contentStatuses.PUBLISHED, title: 'Población', summaryValidated: false, total: 'Información pendiente de validación oficial', urbanRural: 'Información pendiente de validación oficial', growth: 'Información pendiente de validación oficial', communities: [], source: 'Información pendiente de validación oficial', year: 'Pendiente' },
    territorialArea: { status: contentStatuses.PUBLISHED, summaryValidated: false, valueKm2: '', source: 'Información pendiente de validación oficial', year: 'Pendiente' },
    economy: { status: contentStatuses.PUBLISHED, title: 'Economía', generalDescription: 'Descripción demo neutral pendiente de validación oficial.', agriculture: 'Información pendiente de validación oficial', commerce: 'Información pendiente de validación oficial', productiveActivities: [], summaryValidated: false, employmentEntrepreneurship: 'Información pendiente de validación oficial', opportunities: 'Información pendiente de validación oficial', officialFigures: 'Información pendiente de validación oficial', source: 'Información pendiente de validación oficial' },
    landmarks: [{ id: 'lugar-demo', status: contentStatuses.PUBLISHED, name: 'Lugar emblemático demo', photoUrl: './assets/placeholder-landmark.svg', description: 'Descripción demo pendiente de validación oficial.', importance: 'Información pendiente de validación oficial', location: 'Información pendiente de validación oficial' }],
    authorities: municipalConfig.institutionalContent.authorities,
    council: municipalConfig.institutionalContent.council,
  },
};
